@startuml System Use Cases
left to right direction
skinparam actorStyle Hollow 
actor "Web browser\napp session" as browserSession
rectangle "Solidmarks web\nbrowser extension" <<Component>> {
    usecase "Start bookmarks\nsync session" as startSession
    usecase "Authenticate" as authenticate
    usecase "Reconcile bookmarks" as reconcileBookmarks
    usecase "Handle bookmarks update" as handleUpdate
    usecase "Handle update\nnotification from POD" as handleNotification
    usecase "Update bookmarks\nin browser" as updateInBrowser
}
skinparam actorStyle awesome
actor "Solid\nidentity\nprovider" as identityProvider
actor "Solid POD\nprovider" as podProvider
browserSession -- startSession
startSession .right.> authenticate : include
startSession .left.> reconcileBookmarks : include
authenticate -- identityProvider
reconcileBookmarks -- podProvider
browserSession -- handleNotification
browserSession -- updateInBrowser
handleNotification -left-|> handleUpdate
updateInBrowser -right-|> handleUpdate
handleNotification -- podProvider
updateInBrowser -- podProvider
@enduml
